### ISSUE TITLE
Border scores for individual samples?

### ISSUE THREAD

**Issue by martinaryee** [zrmacc/DCS#1]
BorderScores calculates a border score for each sample group. Is it possible to calculate border scores for individual samples, rather than "per-group" scores? If I try to give each sample its own group I get the following error:

```
> A1 = DCS::Auxin_rep1;
> C1 = DCS::Control_rep1;
> Auxin1 = DCS::createDCSsmp(L=A1,chr=c("1","2"),smp="Aux.R1",group=0);
> Ctrl1 = DCS::createDCSsmp(L=C1,chr=c("1","2"),smp="Ctrl.R1",group=1);
> Exp = DCS::createDCSexp(L=list(Auxin1, Ctrl1))
> B <- DCS::BorderScores(Exp)
Error in { : 
  task 1 failed - "task 1 failed - "undefined columns selected""
```

**Comment by zrmacc** [comment]
Thanks, the BorderScores function has been updated, the example should now run without errors.
